"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "./Provider";
import Navbar from "../components/Navbar"
import { Nunito } from "next/font/google"
import { useEffect, useState } from "react";
import { UserLocationContext } from "@/context/userLocation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "RoadRestro",
//   description: "Generated by create next app",
// };

const nunito = Nunito({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [userCurrLocation, setUserCurrLocation] = useState<{
    lat: number | null;
    lng: number | null;
  }>({ lat: null, lng: null });
  const getUserLocation = () => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (pos) => {
          console.log("Position:", pos);
          setUserCurrLocation({
            lat: pos.coords.latitude,
            lng: pos.coords.longitude
          })
        },
        (error) => {
          console.error("Error fetching location:", error);
        }
      );
    } else {
      console.error("Geolocation is not supported by this browser.");
    }
  };
  useEffect(() => {
    getUserLocation();
  }, [])

  return (
    <html lang="en">
      <body
        className={nunito.className}
      >
        <Provider>
          <UserLocationContext.Provider value={{ userCurrLocation, setUserCurrLocation }}>
            <div>
              <Navbar />
            </div>
            {children}

          </UserLocationContext.Provider>
        </Provider>
      </body>
    </html>
  );
}
